'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

// FIX 7: Removed email invite step entirely — DM shares CAMP code verbally
// Step 1: Create campaign → Step 2: Done (show CAMP code, go to dashboard)

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyRecord = Record<string, any>

const TONES = [
  { id: 'dark',    label: 'Dark',    desc: 'Grim, morally complex, heavy' },
  { id: 'heroic',  label: 'Heroic',  desc: 'High stakes, clear purpose, earned triumph' },
  { id: 'comedic', label: 'Comedic', desc: 'Loose, fun, moments of genuine levity' },
  { id: 'mystery', label: 'Mystery', desc: 'Intrigue, unreliable information, slow reveals' },
]

export default function OnboardingDM() {
  const router = useRouter()
  const [step, setStep] = useState<1 | 2>(1)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  // FIX 4: store campaign_code (CAMP-XXXX) not the UUID
  const [campaignCode, setCampaignCode] = useState('')
  const [campaignName, setCampaignName] = useState('')

  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [tone, setTone] = useState('')
  const [copied, setCopied] = useState(false)

  async function createCampaign() {
    setLoading(true)
    setError('')
    try {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) throw new Error('Not authenticated')
      const db = (t: string) => (supabase.from(t) as AnyRecord)

      // Ensure profile has role='dm'
      const { data: existingProfile } = await db('profiles').select('id, role').eq('id', user.id).single()
      if (!existingProfile) {
        await db('profiles').insert({ id: user.id, username: user.email?.split('@')[0] || null, role: 'dm' })
      } else if ((existingProfile as { role: string }).role !== 'dm') {
        await db('profiles').update({ role: 'dm' }).eq('id', user.id)
      }

      // Create campaign — campaign_code is generated by DB trigger
      const { data: campaign, error: err } = await db('campaigns')
        .insert({ dm_id: user.id, name, description: `${tone ? `[${tone}] ` : ''}${description}` })
        .select('id, name, campaign_code')
        .single()

      if (err) throw new Error(err.message)

      // FIX 4: store the CAMP-XXXX-XXXX code, never the UUID
      const code = (campaign as AnyRecord).campaign_code
      if (!code) {
        // campaign_code trigger may not have run — try fetching it
        const { data: refreshed } = await db('campaigns').select('campaign_code').eq('id', (campaign as AnyRecord).id).single()
        setCampaignCode((refreshed as AnyRecord)?.campaign_code || 'Check dashboard for code')
      } else {
        setCampaignCode(code)
      }
      setCampaignName((campaign as AnyRecord).name || name)
      setStep(2)
    } catch (e) {
      setError(`Could not create campaign: ${e instanceof Error ? e.message : String(e)}`)
    }
    setLoading(false)
  }

  function copyCode() {
    navigator.clipboard.writeText(campaignCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <main style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-start', padding: '48px 24px', background: 'var(--bg)' }}>
      <div style={{ width: '100%', maxWidth: 420 }}>
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <h1 style={{ fontSize: 22, fontWeight: 600, color: 'var(--text)', letterSpacing: '-0.02em' }}>In Character</h1>
          <p style={{ fontSize: 13, color: 'var(--text3)', marginTop: 4 }}>DM Setup</p>
        </div>

        {/* Progress dots */}
        <div style={{ display: 'flex', gap: 6, justifyContent: 'center', marginBottom: 32 }}>
          {[1, 2].map(s => (
            <div key={s} style={{ borderRadius: 3, transition: 'all 0.3s', height: 6, width: s === step ? 20 : 6, background: s <= step ? 'var(--accent)' : 'var(--border2)' }} />
          ))}
        </div>

        {/* Step 1: Create campaign */}
        {step === 1 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            <h2 style={{ fontSize: 17, fontWeight: 500, color: 'var(--text)' }}>Create your campaign</h2>

            <div>
              <p style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase', color: 'var(--text3)', marginBottom: 6 }}>Campaign Name</p>
              <input value={name} onChange={e => setName(e.target.value)}
                style={{ width: '100%', background: 'var(--surface)', border: '0.5px solid var(--border2)', color: 'var(--text)', fontSize: 15, borderRadius: 7, padding: '9px 12px', outline: 'none', fontFamily: 'inherit' }}
                placeholder="The Shattered Crown" />
            </div>

            <div>
              <p style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase', color: 'var(--text3)', marginBottom: 6 }}>Description (optional)</p>
              <textarea value={description} onChange={e => setDescription(e.target.value)}
                style={{ width: '100%', background: 'var(--surface)', border: '0.5px solid var(--border2)', color: 'var(--text)', fontSize: 14, borderRadius: 7, padding: '9px 12px', outline: 'none', fontFamily: 'inherit', minHeight: 80, resize: 'vertical' }}
                placeholder="What's this campaign about?" />
            </div>

            <div>
              <p style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase', color: 'var(--text3)', marginBottom: 8 }}>Tone</p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
                {TONES.map(t => (
                  <button key={t.id} onClick={() => setTone(t.id)}
                    style={{ padding: '10px 12px', textAlign: 'left', background: 'var(--surface)', border: `0.5px solid ${tone === t.id ? 'var(--accent)' : 'var(--border2)'}`, borderRadius: 8, cursor: 'pointer' }}>
                    <p style={{ fontSize: 12, fontWeight: 600, color: tone === t.id ? 'var(--accent-text)' : 'var(--text)', marginBottom: 2 }}>{t.label}</p>
                    <p style={{ fontSize: 11, color: 'var(--text3)' }}>{t.desc}</p>
                  </button>
                ))}
              </div>
            </div>

            {error && <p style={{ fontSize: 13, color: 'var(--danger)', background: 'var(--danger-faint)', padding: '8px 12px', borderRadius: 6 }}>{error}</p>}

            <button className="btn-primary" onClick={createCampaign}
              disabled={!name.trim() || loading}
              style={{ width: '100%', fontSize: 14, padding: '10px' }}>
              {loading ? 'Creating...' : 'Create Campaign →'}
            </button>
          </div>
        )}

        {/* Step 2: Done — show CAMP code (FIX 4: never UUID) */}
        {step === 2 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 24, textAlign: 'center' }}>
            <div>
              <div style={{ fontSize: 32, marginBottom: 12 }}>✦</div>
              <h2 style={{ fontSize: 17, fontWeight: 500, color: 'var(--text)', marginBottom: 6 }}>{campaignName} is ready.</h2>
              <p style={{ fontSize: 14, color: 'var(--text2)', lineHeight: 1.6 }}>
                Share your campaign code with players. They enter it during onboarding or in Settings.
              </p>
            </div>

            {/* FIX 4: Campaign code display — CAMP-XXXX-XXXX, never UUID */}
            <button onClick={copyCode}
              style={{ background: 'var(--surface)', border: `0.5px solid var(--border2)`, borderRadius: 10, padding: '20px 24px', cursor: 'pointer', width: '100%' }}>
              <p style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase', color: 'var(--text3)', marginBottom: 8 }}>Campaign Code</p>
              <p style={{ fontSize: 26, fontWeight: 300, letterSpacing: '0.06em', color: 'var(--accent)', fontFamily: 'monospace', marginBottom: 8 }}>
                {campaignCode}
              </p>
              <p style={{ fontSize: 12, color: 'var(--text3)' }}>{copied ? 'Copied!' : 'Tap to copy'}</p>
            </button>

            <p style={{ fontSize: 13, color: 'var(--text3)', lineHeight: 1.6 }}>
              No email invites needed. Players sign up and enter this code. You&apos;ll see them on your dashboard when they&apos;re in.
            </p>

            <button className="btn-primary" onClick={() => router.push('/dm/dashboard')}
              style={{ width: '100%', fontSize: 14, padding: '10px' }}>
              Go to Dashboard →
            </button>
          </div>
        )}
      </div>
    </main>
  )
}
